version: 2.1

description: Tasks for managing Ruby gems in CircleCI builds

display:
  home_url: "https://github.com/boxt/orbs"
  source_url: "https://github.com/boxt/bundler-orb/blob/master/config.yml"

commands:
  audit:
    steps:
      - run:
          name: "Bundle audit"
          command: |
            gem install bundle-audit
            bundle-audit check --update

  cache-read:
    steps:
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}

  cache-write:
    steps:
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
            - ~/.bundle/config

  install:
    steps:
      - run:
          name: "Install bundler and dependencies"
          command: |
            gem install bundler -v=2.2.18
            bundle config set path vendor/bundle
            bundle config set clean true
            bundle config set with ci
            bundle config jobs set with 3
            bundle check || bundle install
