version: 2.1

description: Tasks for managing Ruby gems in CircleCI builds

display:
  home_url: "https://github.com/boxt/orbs"
  source_url: "https://github.com/boxt/bundler-orb/blob/main/config.yml"

commands:
  cache-read:
    steps:
      - restore_cache:
          keys:
            - bundle-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
          name: "Restore Bundler gems cache"
  cache-write:
    steps:
      - save_cache:
          key: bundle-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
          name: "Save Bundler gems cache"
          paths:
            - ./vendor/bundle
            - ./.bundle/config
  install:
    parameters:
      bundler_version:
        description: Version of bundler to install and use
        type: string
        default: "2.3.10"
    steps:
      - run:
          name: "Install Bundler and gems"
          command: |
            gem install bundler --no-document -v << parameters.bundler_version >>
            bundle config set path vendor/bundle
            bundle config set clean true
            bundle config set with ci
            bundle config jobs set with 3
            bundle check || bundle install
