version: 2.1

description: Tasks for managing Ruby gems in CircleCI builds

display:
  home_url: "https://github.com/boxt/orbs"
  source_url: "https://github.com/boxt/bundler-orb/blob/main/config.yml"

commands:
  cache-read:
    parameters:
      version:
        description: Version of the cache to restore
        type: string
        default: "v1"
    steps:
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - bundle-cache-<< parameters.version >>-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - bundle-cache-<< parameters.version >>-{{ .Branch }}-
            - bundle-cache-<< parameters.version >>-
          name: "Restore Bundler gems cache"

  cache-write:
    parameters:
      version:
        description: Version of the cache to save
        type: string
        default: "v1"
    steps:
      - save_cache:
          key: bundle-cache-<< parameters.version >>-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          name: "Save Bundler gems cache"
          paths:
            - ./.bundle/config
            - ./vendor/bundle

  install:
    parameters:
      bundler_version:
        description: Version of bundler to install and use
        type: string
        default: "2.3.36"
    steps:
      - run:
          name: "Install Bundler and gems"
          command: |
            gem install bundler --no-document -v << parameters.bundler_version >>
            bundle config set path vendor/bundle
            bundle config set clean true
            bundle config set without seeding
            bundle install
