version: 2.1

description: Tasks for managing Ruby gems in CircleCI builds

display:
  home_url: "https://github.com/boxt/orbs"
  source_url: "https://github.com/boxt/bundler-orb/blob/master/config.yml"

commands:
  cache-read:
    steps:
      - restore_cache:
          keys:
            - gem-cache-{{ checksum "Gemfile.lock" }}

  cache-write:
    steps:
      - save_cache:
          key: gem-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - ./vendor/bundle
            - ~/.bundle/config

  install:
    parameters:
      bundler_version:
        description: Version of bundler to install and use
        type: string
        default: "2.2.33"
    steps:
      - run:
          name: "Install bundler and dependencies"
          command: |
            gem install bundler --no-document -v << parameters.bundler_version >>
            bundle config set path vendor/bundle
            bundle config set clean true
            bundle config set with ci
            bundle config jobs set with 3
            bundle check || bundle install
